/**
 * One sidebar per audience track (Discover · Get started · User guide · Develop · Research ·
 * Community), each autogenerated from its own top-level folder under docs/. The navbar links each
 * audience to its own sidebar via `docSidebar` items — see docusaurus.config.js.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  discoverSidebar: [{type: 'autogenerated', dirName: 'discover'}],
  getStartedSidebar: [{type: 'autogenerated', dirName: 'get-started'}],
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  developSidebar: [{type: 'autogenerated', dirName: 'develop'}],
  researchSidebar: [{type: 'autogenerated', dirName: 'research'}],
  communitySidebar: [{type: 'autogenerated', dirName: 'community'}],
};

module.exports = sidebars;
