/**
 * One sidebar per audience track (Discover · Get started · User guide · Develop · Research ·
 * Community), each autogenerated from its own top-level folder under docs/. The navbar links each
 * audience to its own sidebar via `docSidebar` items — see docusaurus.config.js.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  discoverSidebar: [{type: 'autogenerated', dirName: 'discover'}],
  getStartedSidebar: [{type: 'autogenerated', dirName: 'get-started'}],
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  developSidebar: [
    {type: 'autogenerated', dirName: 'develop'},
    {type: 'link', label: 'Components', href: '/docs/components'},
  ],
  researchSidebar: [
    {type: 'autogenerated', dirName: 'research'},
    {type: 'link', label: 'Publications', href: '/papers'},
    {type: 'link', label: 'People', href: '/contributors'},
  ],
  communitySidebar: [
    {type: 'autogenerated', dirName: 'community'},
    {type: 'link', label: 'Partners', href: '/partners'},
  ],
};

module.exports = sidebars;
