#!/usr/bin/env python3
"""Regenerate docs/develop/components.md.

Source of truth: src/data/components.json (generic frameworks and core components) and
src/data/technology-adapters.json (the technology adapter registry, also used by
generate_repository_map.py). Python standard library only: this repository's package-lock.json
cannot be regenerated, so nothing here may add an npm dependency, and only the generated page is
committed.

Run from the website repo root:

    python3 scripts/generate_components_page.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# The only technology adapters that ever had a mini-site actually built (see the 2026-09 site
# audit): every other adapter links to its GitHub repository instead of a fabricated mini-site URL.
MINISITE_IDS = {"diagram", "emf", "owl", "http", "jdbc", "pdf", "kafka"}

STATUS_LABELS = {
    "stabilised": "Stabilised",
    "migration-in-progress": "Migration in progress",
    "active-development": "Active development",
    "limited-support": "Limited support",
    "retired": "Retired",
    "unclassified": "Not yet classified",
}
STATUS_ORDER = list(STATUS_LABELS)


def load(name):
    return json.loads((ROOT / "src" / "data" / name).read_text())


def link_list(items):
    return "\n".join(f"- [{label}]({url})" for label, url in items)


def description_table(rows):
    lines = ["| Name | Description |", "|---|---|"]
    for label, url, description in rows:
        lines.append(f"| [{label}]({url}) | {description} |")
    return "\n".join(lines)


def build_page():
    components = load("components.json")
    registry = load("technology-adapters.json")["adapters"]

    generic = link_list((c["name"], c["url"]) for c in components["generic"])
    core = link_list((c["name"], c["source"]) for c in components["core"])

    ta_sections = []
    for status in STATUS_ORDER:
        adapters = [a for a in registry if a["status"] == status]
        if not adapters:
            continue
        rows = []
        for a in adapters:
            url = f"https://openflexo.org/openflexo-{a['id']}/" if a["id"] in MINISITE_IDS else a["repository"]
            rows.append((a["name"], url, a["description"]))
        ta_sections.append(f"### {STATUS_LABELS[status]}\n\n{description_table(rows)}")
    ta_block = "\n\n".join(ta_sections)

    return f"""---
sidebar_position: 7
title: Components
description: The generic frameworks, the core components and the technology adapters, with their status.
---

# Components

<!-- Generated by scripts/generate_components_page.py from src/data/components.json and
     src/data/technology-adapters.json. Do not hand-edit -- re-run the script instead. -->

## Generic frameworks

Reusable outside model federation.

{generic}

## Core components

{core}

## Technology adapters

A few adapters below (Diagram, EMF, OWL, HTTP, JDBC, PDF, Kafka) link to a per-component
mini-site — content from 2023–2024, describing an older version of Openflexo, not being rebuilt
yet. Every other adapter links straight to its source repository instead. Status reflects the
architecture board's review of 2026-04-03; see the [repository map](./repository-map) for every
repository grouped by architectural role instead of by status.

{ta_block}
"""


def main():
    out = ROOT / "docs" / "develop" / "components.md"
    out.write_text(build_page())
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
